package com.dfsp.dashboard.model;

import lombok.Data;

@Data
public class MarketModel {

    private String year;
    private String type;
    private String insurance_group;
    private String direct;
    private String direct_active;
    private String insurer;
    private String nep_py;
    private String nep_cy;
    private String nep_yty_cy_procent;
    private String nep_yty_cy_pln;
    private String gwp_py;
    private String gwp_cy;
    private String gwp_yty_cy_procent;
    private String gwp_yty_cy_pln;
    private String market_share_py;
    private String market_share_cy;
    private String group_cy_procent;
    private String individual_cy_procent;
    private String periodical_cy_procent;
    private String single_cy_procent;
    private String non_bonus_cy_procent;
    private String bonus_cy_procent;
    private String investment_risk_is_borne_by_policyholders_cy_procent;
    private String gwp_group_cy;
    private String gwp_individual_cy;
    private String gwp_periodical_cy;
    private String gwp_single_cy;
    private String gwp_non_bonus__cy;
    private String gwp_bonus_cy;
    private String gwp_investment_risk_is_borne_by_policyholders_cy;
    private String claims_incurred_py;
    private String claims_incurred_cy;
    private String claims_incurred_cy_yty_procent;
    private String claims_incurred_to_nep_cy_ratio;
    private String gross_claims_paid_py;
    private String gross_claims_paid_cy;
    private String gross_claims_paid_cy_yty_procent;
    private String claims_paid_to_nep_cy;
    private String subscribed_capitals_py;
    private String subscribed_capitals_cy;
    private String casco_ms_cy;
    private String liability_ms_cy;
    private String motor_ms_cy;
    private String other_lob_ms_cy;
    private String casco_procent_cy;
    private String liability_procentcy;
    private String motor_procent_cy;
    private String casco_pln_cy;
    private String liability_gwp_cy;
    private String motor_gwp_cy;
    private String other_lob_gwp_cy;
    private String direct_gwp_;
    private String direct_market_share;
    private String media_invest_rate_table;
    private String media_invest_real_costs;
    private String sov;
    private String media_invest_to_direct_premium_procent;
    private String technical_result_py;
    private String technical_result_procent;
    private String change;
    private String operating_expenses_py;
    private String operating_expenses_cy;
    private String operating_exp_yoy;
    private String acquisition_costs_py;
    private String acquisition_costs_cy;
    private String acquisition_costs_yoy;
    private String administrative_expenses_py;
    private String administrative_expenses_cy;
    private String administrative_expenses_yoy;
    private String reinsurance_commissions_and_profit_participation_py;
    private String reinsurance_commissions_and_profit_participation_cy;
    private String reinsurance_commissions_and_profit_participation_yoy;
    private String investments_py;
    private String investments_cy;
    private String investments_yoy;
    private String investments_result_py;
    private String investments_result_cy;
    private String investments_result_cy_yoy;
    private String investments_result_py_procent;
    private String investments_result_cy_procent;
    private String gross_profit_py;
    private String gross_profit_cy;
    private String gross_profit_yoy;
    private String net_profit_py;
    private String net_profit_cy;
    private String net_profit_yoy;

}
